code-review request
htmlacademy-htmlcss/2289265-sedona-36 pull request #2
Opened 2023-01-20 11:19 UTC by psikespiegel

помимо основной страницы, разметил так-же модальное окно

2023-01-22 15:53 UTC, pavel-nyukalo requested changes

2023-01-22 15:53 UTC, pavel-nyukalo commented on index.html
> +  </nav>
Нам важно соблюдать структуру отступов. Все вложенные теги отделяются от родительских двойным пробелом. Можно отформатировать средствами редактора. Но должно быть примерно так

```html
<html>
  <head>
    ...
  </head>
  
  <body> <-- обрати внимание, что у body тоже есть отступы, ибо он вложен в <html>
    <header>
      <a>
        <img>
        <span>...</span>
      </a>
      
      <nav>
        <ul>
          <li><a>...</a></li>
          <li><a>...</a></li>
          <li><a>...</a></li>
        </ul>
      </nav>
      
      и тд
```

2023-01-22 15:53 UTC, pavel-nyukalo commented on index.html
> + </nav>
Тут на навигацию не очень похоже, я бы предложил этот `nav` убрать

2023-01-22 15:53 UTC, pavel-nyukalo commented on index.html
> +
Двойных переносов тоже не должно быть, форматирование поможет сделать по красоте

2023-01-22 15:53 UTC, pavel-nyukalo commented on index.html
> +  </dl>
Хм, я всегда считал эту секцию именно списком и думаю по семантике это именно список преимуществ.

`dl-dt-dd` это больше про список определений

2023-01-22 15:53 UTC, pavel-nyukalo commented on index.html
> +      </dl>
И тут тоже мне кажется это больше список

2023-01-22 15:53 UTC, pavel-nyukalo commented on index.html
> +</div>
1. Тоже можно сделать секцией, а не дивом
2. "Заинтересовались" в целом на заголовок похоже
3. Кнопку лучше сделать ссылкой, чтобы можно было перенаправить на страницу с поиском. И можно текст писать по обычным правилам - "Поиск гостиницы в Седоне", а уже в верхний регистр сделаем через css

2023-01-22 15:53 UTC, pavel-nyukalo commented on index.html
> +    </div>
1. Тут также больше на секцию похоже
2. "Подпишитесь" тоже на заголовок больше походит
3. `label` нужен да, даже скрытый. По критерию так
4. `input type="submit"` лучше заменить на `button type="submit"`. В таком случае мы можем более гибко управлять содержимым тега, и вставлять не только текст

2023-01-22 15:53 UTC, pavel-nyukalo commented on index.html
> +          <li class="footer-socials-vk"><a class="button" href="https://vk.com/htmlacademy"></a><span class="visually-hidden">ВКонтакте</span></li>
Скрытая подпись должна лежать внутри того, что она описывает. То бишь внутри ссылки

2023-01-22 15:53 UTC, pavel-nyukalo commented on index.html
> +<input type="submit" value="Найти">
Так же заменить на кнопку

2023-01-22 15:53 UTC, pavel-nyukalo commented on index.html
> +</div>
И отступы поправить вот как раз

2023-01-22 15:53 UTC, pavel-nyukalo commented on catalog.html
> +</header>
Аналогичные замечания

2023-01-22 15:53 UTC, pavel-nyukalo commented on catalog.html
> +    </fieldset>
Так же нужно отступы поправить

2023-01-22 15:53 UTC, pavel-nyukalo commented on catalog.html
> +      <input type="reset" value="Сбросить">
Тут тоже лучше на кнопку с таким же type заменить

2023-01-22 15:53 UTC, pavel-nyukalo commented on catalog.html
> +<footer class="main-footer">
К футеру аналогичные замечания

2023-01-24 03:45 UTC, psikespiegel commented
много замечаний об отступах, я в тот момент ещё не знал о существовании форматирования.

2023-01-24 03:46 UTC, psikespiegel commented
Так же я ещё не совсем понял важность и необходимость EditConfig, если все отступы и форматирование делается в vs code.

2023-01-24 10:33 UTC, pavel-nyukalo requested changes

2023-01-24 10:33 UTC, pavel-nyukalo commented on index.html
> +        </span>
Этот спан кстати лишний, поскольку его содержимое можно будет поместить в `alt` картинки

2023-01-24 10:33 UTC, pavel-nyukalo commented on index.html
> +
Таких двойных отступов у нас не должно быть, максимум один перенос

![image](https://user-images.githubusercontent.com/52506235/214268675-2ebe7ee8-1860-45e1-be1c-c3358dbd0703.png)

2023-01-24 10:33 UTC, pavel-nyukalo commented on index.html
> +                class="visually-hidden">ВКонтакте</span></a></li>
Такую большую вложенность лучше разбить на несколько строк, для удобочитаемости

```html
<li class="footer-socials-vk">
  <a class="button" href="https://vk.com/htmlacademy">
    <span class="visually-hidden">ВКонтакте</span>
  </a>
</li>
```

2023-01-24 10:33 UTC, pavel-nyukalo commented on catalog.html
> +        <h2><span class="visually-hidden">Фильтр поиска</span></h2>
По сути, спан лишний. Это у нас скрытый заголовок, поэтому мы можем `visually-hidden` прямо на него повесить

```html
<h2 class="visually-hidden">Фильтр поиска</h2>
```

2023-01-24 10:33 UTC, pavel-nyukalo commented on catalog.html
> +                  Бассейн</label></li>
Так же лучше разбить на несколько строк

2023-01-24 10:33 UTC, pavel-nyukalo commented on catalog.html
> +              </a>
`<a>`  тоже лучше на новую строку перенести

2023-01-24 10:37 UTC, psikespiegel commented on index.html
> +        </span>
done

2023-01-24 10:37 UTC, psikespiegel commented on index.html
> +
видимо, случайно. но буду знать, что 1 - это максимум

2023-01-24 10:39 UTC, psikespiegel commented on index.html
> +                class="visually-hidden">ВКонтакте</span></a></li>
починил весь список

2023-01-24 10:41 UTC, psikespiegel commented on catalog.html
> +        <h2><span class="visually-hidden">Фильтр поиска</span></h2>
там как раз в общем чате был спор, стоит ли инфу из h оборачивать в span, чтоб скрыть. хотел у тебя спросить. а теперь есть ответ

2023-01-24 10:42 UTC, psikespiegel commented on catalog.html
> +                  Бассейн</label></li>
done

2023-01-24 10:45 UTC, psikespiegel commented on catalog.html
> +              </a>
во всём списке починил

2023-01-25 06:30 UTC, pavel-nyukalo approved these changes

2023-01-25 06:34 UTC, merged