Базовая стилизация всех страниц
htmlacademy-htmlcss/2289265-sedona-36 pull request #4
Opened 2023-01-31 13:42 UTC by psikespiegel

---
:mortar_board: [Базовая стилизация всех страниц](https://up.htmlacademy.ru/htmlcss/36/user/2289265/tasks/8)

2023-02-03 07:57 UTC, pavel-nyukalo requested changes

2023-02-03 07:57 UTC, pavel-nyukalo commented on catalog.html
> +          <li><a href="catalog.html">Гостиницы</a></li>
Наоборот должно быть в каталоге - "Главная" должна вести в `index`, а вот с "Гостиницы" можно убрать ссылку

2023-02-03 07:57 UTC, pavel-nyukalo commented on catalog.html
> +
![image](https://user-images.githubusercontent.com/52506235/216541671-c7bf3d4d-5479-409e-a4f3-4fa177dfb162.png)

Про секцию тоже нужно поправить (то что ей заголовок требуется). Спека это подчеркивает как `warning`, но критерии требуют наличие заголовков у секций

2023-02-03 07:57 UTC, pavel-nyukalo commented on catalog.html
> +              <h3>Amara Resort & Spa</h3>
Почему решил убрать ссылку? На ретро что-то было про это?

2023-02-03 07:57 UTC, pavel-nyukalo commented on catalog.html
> +          <li class="pagination-10">
Вот тут я бы все же оставил `pagination-item`. Давай сравним

```css
.pagination-item {
  ...
  ...
  ...
}
```

или

```css
.pagination-1,
.pagination-2,
.pagination-3,
.pagination-4,
.pagination-5,
.pagination-6,
.pagination-7,
.pagination-8,
.pagination-9,
.pagination-10 {
  ...
  ...
  ...
}
```

или еще хуже

```css
.pagination-1 {
  ...
  ...
  ...
}

.pagination-2 {
  ...
  ...
  ...
}

.pagination-3 {
  ...
  ...
  ...
}

.pagination-4 {
  ...
  ...
  ...
}

.pagination-5 {
  ...
  ...
  ...
}

.pagination-6 {
  ...
  ...
  ...
}

.pagination-7 {
  ...
  ...
  ...
}

.pagination-8 {
  ...
  ...
  ...
}

.pagination-9 {
  ...
  ...
  ...
}

.pagination-10 {
  ...
  ...
  ...
}
```

Если нужно будет что-то конкретному элементу поправить, то сделаем это доп. классом

2023-02-03 07:57 UTC, pavel-nyukalo commented on catalog.html
> +        <ul class="footer-socials">
Вот как раз выше писал, заголовок здесь нужен. Можно скрытый

2023-02-03 07:57 UTC, pavel-nyukalo commented on index.html
> +            <img src="images/index/advantages-bridge.jpg" width="800" height="385" alt="Мост дьявола.">
Здесь кстати можно картинку перед `div` расположить, для простоты стилизации. Но это на будущее

```html
<li class="advantages-item">
  <img src="images/index/advantages-bridge.jpg" width="800" height="385" alt="Мост дьявола.">
  <div>
    <h3>Там есть
      мост дьявола</h3>
    <p>Да, по нему можно пройти! Если вы осмелитесь, разумеется</p>
  </div>
</li>
```

2023-02-03 07:57 UTC, pavel-nyukalo commented on index.html
> +      <section class="footer-socials">
Тут так же соответственно, если стала секция - ей нужен заголовок

2023-02-03 07:57 UTC, pavel-nyukalo commented on styles/style.css
> +}
Потом не забудь доработать этот класс, поскольку там несколько другие свойства

2023-02-03 07:57 UTC, pavel-nyukalo commented on styles/style.css
> +.advantages-item:last-child p {
Думаю более надежно завязаться на дополнительный класс, нежели на порядок элементов. Поменяется порядок - и все уже не так как нужно будет

2023-02-03 07:57 UTC, pavel-nyukalo commented on styles/style.css
> +.advantages-item:nth-child(3) {
Аналогично

2023-02-03 07:57 UTC, pavel-nyukalo commented on styles/style.css
> +.more-advantages-item:last-child {
+1

2023-02-03 07:57 UTC, pavel-nyukalo commented on styles/style.css
> +  color: #ffffff;
Предлагаю писать значения HEX единообразно. Либо в верхнем регистре (`#82B3D3` и `#FFFFFF`), либо в нижнем (`#82b3d3` и `#ffffff`). И везде так

2023-02-06 05:48 UTC, psikespiegel commented on styles/style.css
> +.more-advantages-item:last-child {
как выяснилось, этих двух вообще не должно быть, я потом присмотрела, такие же свойства у большинства преимуществ, поэтому я вынес это в отдельное правило

2023-02-07 06:50 UTC, pavel-nyukalo requested changes

2023-02-07 06:50 UTC, pavel-nyukalo commented on catalog.html
> +          </a>
Я бы отформатировал тут, чтобы открывающая ссылка была на новой строке

```html
<div class="nav-flex">
  <a class="main-page">
    <img class="header-logo" src="images/header/logo-header.svg" width="140" height="70" alt="Логотип сайта Седона.">
  </a>
  ...
```

(и в целом мне кажется `div` тут лишний, мы сможем спокойно стилизовать и через `header`)

2023-02-07 06:50 UTC, pavel-nyukalo commented on catalog.html
> +            <li><a href="catalog.html">Гостиницы</a></li>
Вот здесь не исправлено:
"Главная" должна быть с `href` на `index.html`

2023-02-07 06:50 UTC, pavel-nyukalo commented on catalog.html
> +      <main class="main-inner">
![image](https://user-images.githubusercontent.com/52506235/217167765-8c64e26e-b6d5-4b23-98de-1eaf43c9d67f.png)

2023-02-07 06:50 UTC, pavel-nyukalo commented on index.html
> +            <img class="header-logo" src="images/header/logo-header.svg" width="140" height="70"
Тут так же как написал выше

2023-02-07 06:50 UTC, pavel-nyukalo commented on styles/style.css
> +}
1. Очень ненадежный селектор. Если `placeholder` поменяется на например "Ваш E-mail", то правило перестанет работать. Я бы лучше на класс завязывался
2. При указании семейства шрифта необходимо так же добавлять общее семейство
![image](https://user-images.githubusercontent.com/52506235/217169079-b5febcd3-6137-4584-93c0-faca42ff8207.png)

Но можно немного другим путем пойти - тем элементам, что не наследуют шрифт по-умолчанию (кнопки, инпуты и тд) указать `font-family: inherit`. И тогда не придется им прописывать в явном виде семейство шрифтов

2023-02-08 08:47 UTC, pavel-nyukalo approved these changes

2023-02-08 08:48 UTC, merged