декоративные элементы
htmlacademy-htmlcss/2289265-sedona-36 pull request #7
Opened 2023-02-25 09:20 UTC by psikespiegel

2023-02-26 15:52 UTC, pavel-nyukalo requested changes

2023-02-26 15:52 UTC, pavel-nyukalo commented on catalog.html
> +                </div>
Насчет звезд. Как бы я предложил сделать.
Положить их все-таки фоном, чтобы не засорять разметку, и дать им `background-repeat: space`. А уже дополнительными классами менять ширину, чтобы показывалось разное кол-во звезд

2023-02-26 15:52 UTC, pavel-nyukalo commented on styles/style.css
> +
Насчет этой черточки. Получается не очень универсально. Во-первых, для каждой ссылки придется делать доп. класс. Во-вторых, представь если поменяется текст хотя бы на букву. Придется переделывать

Я бы предложил сделать следующим образом:
- даем ширину в 100% от ссылки
- но у ссылки есть паддинги, а нам надо чтобы только по тексту все было. В таком случае делаем `width: calc(100% - 32px)` 32 - это 16 слева и 16 справа

![image](https://user-images.githubusercontent.com/52506235/221420619-30644ede-d131-4023-8a4d-dc577c4f0d60.png)

2023-02-26 15:52 UTC, pavel-nyukalo commented on styles/style.css
> +  background-image: url("/images/index/rec.svg");
Тут нужно `../images`, иначе на опубликованной версии не отображается

![image](https://user-images.githubusercontent.com/52506235/221420778-5f602990-ed68-4b3c-9584-590e6025b4e4.png)

2023-02-26 15:52 UTC, pavel-nyukalo commented on styles/style.css
> +  background-image: url("/images/index/rec.png");
+1

2023-02-26 15:52 UTC, pavel-nyukalo commented on styles/style.css
> +}
Тут нужно поработать над переполнением. Если добавится элементов, то во-первых, между ними нет отступа, во-вторых стрелочка отображается только у последнего, а по идее надо чтобы между каждым было

![image](https://user-images.githubusercontent.com/52506235/221420951-267a338b-319e-4366-ae98-ce8ba6840a11.png)

Я бы пошел от обратного, то есть добавлял бы не последнему, а каждому, кроме последнего

2023-02-26 15:52 UTC, pavel-nyukalo commented on styles/style.css
> +  background-image: url("/images/catalog/checked.svg");
+1 про путь

2023-02-26 15:52 UTC, pavel-nyukalo commented on styles/style.css
> +  background-image: url("/images/catalog/radio.svg");
+1

2023-02-26 15:52 UTC, pavel-nyukalo commented on styles/style.css
> +.radio-input:focus + .radio-custom {
Еще нужно добавить состояние `disabled` для чекбоксов и радио, к этому часто придираются

2023-02-26 15:52 UTC, pavel-nyukalo commented on styles/style.css
> +
Лишняя пустая строка добавилась

2023-02-27 08:25 UTC, psikespiegel commented on styles/style.css
> +
ширину выставил, как ты сказал, всё работает, даже на длинных текстах. Но не понял про ```left``` и ```transform```. у меня эти свойства не работают, работают именно что обычные left-right

2023-02-27 08:29 UTC, psikespiegel commented on styles/style.css
> +  background-image: url("/images/index/rec.svg");
исправил пути, все 4. нам ведь всегда надо ```../``` делать, это мы ВЫХОДИМ из папки стилей, и только потом заходим в img, так?

2023-02-27 08:29 UTC, psikespiegel commented on styles/style.css
> +
убрал

2023-03-01 17:34 UTC, pavel-nyukalo commented on styles/style.css
> +  background-image: url("/images/index/rec.svg");
Да, все верно

2023-03-01 17:36 UTC, pavel-nyukalo commented on styles/style.css
> +
`transform` смещает элемент и это такой хак небольшой. Сначала мы сместили элемент в середину родительского (`50%`), теперь он начинается от середины родителя. А потом за счет `transform: translateX(-50%)` смещаем элемент влево на 50% уже его ширины. И таким образом мы отцентрируем

2023-03-01 17:51 UTC, pavel-nyukalo requested changes

2023-03-01 17:51 UTC, pavel-nyukalo commented on catalog.html
> +                </div>
Уже хорошо, но нужно еще вернуть подпись для скринридеров скрытую. По типу "Четыре звезды." и тд

2023-03-01 17:51 UTC, pavel-nyukalo commented on index.html
> +            <button class="calendar-icon" type="button"></button>
В эти кнопочки тоже нужно добавить скрытую подпись, которая скажет, что произойдет если пользователь нажмет

2023-03-01 17:51 UTC, pavel-nyukalo commented on index.html
> +              <button class="pop-up-button">
Так же не забывай указывать `type`

2023-03-01 17:51 UTC, pavel-nyukalo commented on index.html
> +          </button>
Точно ли нужен `span`?

2023-03-01 17:51 UTC, pavel-nyukalo commented on styles/style.css
> +}
Дублировать свойства нет смысла, поскольку они унаследуются от `stars`. А вот доп. классами будем менять только ширину

```css
.stars {
  background-image: url("../images/catalog/star.svg");
  background-repeat: space;
  width: 140px;
  height: 17px;
}

.four-stars {
  width: 89px;
}

.three-stars {
  width: 66px;
}

.two-starts {
  width: 43px;
}
```

Смотри как код сократился

2023-03-01 17:51 UTC, pavel-nyukalo commented on styles/style.css
> +  font-family: 'PT Sans';
Не забываем указывать семейство шрифтов

2023-03-01 17:51 UTC, pavel-nyukalo commented on styles/style.css
> +  font-family: 'PT Sans';
+1

2023-03-01 17:51 UTC, pavel-nyukalo commented on styles/style.css
> +  font-family: 'PT Sans';
+1. В целом надо поглядеть, шрифт наследуюется же

2023-03-01 17:51 UTC, pavel-nyukalo commented on styles/style.css
> +  background-image: url(../images/index/modal-cross.svg);
Кавычки в `url`

2023-03-02 05:37 UTC, psikespiegel commented on index.html
> +          </button>
не нужен

2023-03-02 05:38 UTC, psikespiegel commented on index.html
> +              <button class="pop-up-button">
указал type=button

2023-03-05 19:30 UTC, pavel-nyukalo approved these changes

2023-03-05 19:30 UTC, merged